export const en = {
  common: {
    addProduct: "Add Product",
    takePhoto: "Take photo",
    addPhoto: "Choose photo",
    addMeal: "Add meal",
    addFav: "Add to favourites",
    toast: "Please choose an image",
    error: "Error",
    add: "Add",
    addNew: "Add new"
  },
  navigation: {
    home: "Home",
    favorites: "Favorites",
    profile: "Profile",
    settings: "Settings",
    camera: "Camera",
  },
  camera: {
    return: "Return",
    retakePhoto: "Retake photo",
    noAccess: "No access to camera",
  },
  addScreen: {
    name: "Name",
    enterName: "Enter name",
    calories: "Calories",
    enterCalories: "Enter calories for 100g",
    category: "Category",
    enterCategory: "Enter product category",
    weight: "Weight",
    enterWeight: "Enter weight in grams",
    toastWeight: "Provide meal weight",
    toastCalories: "Provide meal calories",
    loader: "Calorie estimation in progress...",
  },
  editScreen: {
    name: "Name",
    calories: "Calories",
    category: "Category",
    edit: "Edit",
    editMeal: "Edit meal",
    delete: "Delete meal",
    weight: "Weight",
    calories_on_100g:"Calories on 100g"
  },
  categories: {
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    snack: "Snacks",
  },
  settings: {
    changeLang: "Change language",
    selectLang: "Select language",
    eng: "English",
    pl: "Polish",
    darkMode: "Dark mode",
    logOut: "Log out",
  },
};
