export const en = {
  common: {
    addProduct: "Add Product",
    takePhoto: "Take photo",
    addPhoto: "Choose photo",
    addMeal: "Add meal",
    addFav: "Add to favourites",
    toast: "Please choose an image",
    error: "Error",
    add: "Add",
    addNew: "Add new",
  },
  navigation: {
    home: "Home",
    favorites: "Favorites",
    profile: "Profile",
    settings: "Settings",
    camera: "Camera",
    most_popular: "Most Popular",
  },
  camera: {
    return: "Return",
    retakePhoto: "Retake photo",
    noAccess: "No access to camera",
    notFood: "Food not found on this photo.",
    retakePls: "Please retake photo and try again.",
  },
  addScreen: {
    name: "Name",
    enterName: "Enter name",
    calories: "Calories",
    enterCalories: "Enter calories for 100g",
    category: "Category",
    enterCategory: "Enter product category",
    weight: "Weight",
    enterWeight: "Enter weight in grams",
    toastWeight: "Provide meal weight",
    toastCalories: "Provide meal calories",
    loader: "Calorie estimation in progress...",
  },
  editScreen: {
    name: "Name",
    calories: "Calories",
    category: "Category",
    edit: "Edit",
    editMeal: "Edit meal",
    delete: "Delete meal",
    weight: "Weight",
    calories_on_100g: "Calories on 100g",
  },
  categories: {
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    snack: "Snacks",
  },
  settings: {
    changeLang: "Change language",
    selectLang: "Select language",
    eng: "English",
    pl: "Polish",
    darkMode: "Dark mode",
    logOut: "Log out",
  },
  addProfile: {
    welcome: "Welcome to Calera",
    welcome_txt:
      "Provide your data that will allow us to calculate your daily calorie requirements.",
    age: "Age",
    weight: "Weight",
    weight_kg: "Weight in kilograms",
    height: "Height",
    height_cm: "Height in centimeters",
    gender: "Gender",
    male: "Male",
    objective: "Objective",
    objective1: "Maintain weight",
    objective2: "Lose weight",
    objective3: "Gain weight",
    goalWeight: "What is your weight goal",
    goalWeightChange:"weekly weight change",
    female: "Female",
    activity: "Activity",
    activity_sed: "Sedentary",
    activity_act: "Very active",
    continue: "Continue",
  },
  profile: {
    account: "Account",
    objective: "Objective",
    objective1: "Maintain weight",
    objective2: "Lose weight",
    objective3: "Gain weight",
    objective_calories:"Calories consumed per day:",
    user: "User",
    age: "Age:",
    weight: "Weight:",
    weight_1: "Weight",
    weight_kg: "Weight in kilograms",
    height_cm: "Height in centimeters",
    height: "Height:",
    gender: "Gender:",
    male: "Male",
    female: "Female",
    addNewWeight: "Add new weight record",
    cancel: "Cancel",
    continue: "Continue",
    save: "Save",
  },
};
