export const en = {
  common: {
    addProduct: "Add product",
    takePhoto: "Take photo",
    addPhoto: "Choose photo",
    addMeal: "Add meal",
    toast: "Please choose an image",
    error: "Error",
    add: "Add",
  },
  navigation: {
    home: "Home",
    favorites: "Favorites",
    profile: "Profile",
    settings: "Settings",
    camera: "Camera",
  },
  camera: {
    return: "Return",
    retakePhoto: "Retake photo",
    noAccess: "No access to camera",
  },
  addScreen: {
    name: "Name",
    enterName: "Enter name",
    calories: "Calories",
    enterCalories: "Enter calories for 100g",
    weight: "Weight",
    enterWeight: "Enter weight in grams",
    toastWeight: "Provide meal weight",
    toastCalories: "Provide meal calories",
    loader: "Calorie estimation is in progress...",
  },
  settings: {
    changeLang: "Change language",
    selectLang: "Select language",
    eng: "English",
    pl: "Polish",
    darkMode: "Dark mode",
  },
};
