export const pl = {
  common: {
    addProduct: "Dodaj produkt",
    takePhoto: "Zrób zdjęcie",
    addPhoto: "Dodaj zdjęcie",
    addMeal: "Dodaj posiłek",
    toast: "Proszę wybrać zdjęcie",
    error: "Błąd",
    add: "Dodaj",
  },
  navigation: {
    home: "Strona Główna",
    favorites: "Ulubione",
    profile: "Profil",
    settings: "Ustawienia",
    camera: "Aparat",
  },
  camera: {
    return: "Powrót",
    retakePhoto: "Zrób ponownie",
    noAccess: "Brak dostępu do kamery",
  },
  addScreen: {
    name: "Nazwa",
    enterName: "Podaj nazwę",
    calories: "Kalorie",
    enterCalories: "Wpisz wartość kaloryczną na 100g",
    weight: "Waga",
    enterWeight: "Podaj wagę",
    toastWeight: "Wprowadź wagę posiłku",
    toastCalories: "Wprowadź kaloryczność posiłku",
  },
  settings: {
    changeLang: "Zmień język",
    selectLang: "Wybierz język",
    eng: "Angielski",
    pl: "Polski",
    darkMode: "Tryb ciemny",
  },
};
