export const pl = {
  common: {
    addProduct: "Dodaj Produkt",
    takePhoto: "Zrób zdjęcie",
    addPhoto: "Wybierz zdjęcie",
    addMeal: "Dodaj posiłek",
    addFav: "Dodaj do ulubionych",
    toast: "Proszę wybrać zdjęcie",
    error: "Błąd",
    add: "Dodaj",
    addNew: "Dodaj nowy",
  },
  navigation: {
    home: "Strona Główna",
    favorites: "Ulubione",
    profile: "Profil",
    settings: "Ustawienia",
    camera: "Aparat",
    most_popular: "Najpopularniejsze",
  },
  camera: {
    return: "Powrót",
    retakePhoto: "Ponów",
    noAccess: "Brak dostępu do kamery",
    notFood: "Nie znaleziono jedzenia na tym zdjęciu",
    retakePls: "Powtórz zdjęcie i spróbuj ponownie.",
  },
  addScreen: {
    name: "Nazwa",
    enterName: "Podaj nazwę",
    calories: "Kalorie",
    enterCalories: "Wpisz wartość kaloryczną na 100g",
    category: "Kategoria",
    enterCategory: "Wpisz kategorię potrawy",
    weight: "Waga",
    enterWeight: "Podaj wagę",
    toastWeight: "Wprowadź wagę posiłku",
    toastCalories: "Wprowadź kaloryczność posiłku",
    loader: "Trwa szacowanie kalorii...",
  },
  editScreen: {
    name: "Nazwa",
    calories: "Kalorie",
    category: "Kategoria",
    edit: "Edytuj",
    editMeal: "Edytuj potrawę",
    delete: "Usuń potrawę",
    weight: "Waga",
    calories_on_100g: "Kalorie na 100g",
  },
  categories: {
    breakfast: "Śniadanie",
    lunch: "Lunch",
    dinner: "Kolacja",
    snack: "Przekąski",
  },
  settings: {
    changeLang: "Zmień język",
    selectLang: "Wybierz język",
    eng: "Angielski",
    pl: "Polski",
    darkMode: "Tryb ciemny",
    logOut: "Wyloguj",
  },
  addProfile: {
    welcome: "Witamy w aplikacji Calera",
    welcome_txt:
      "Wprowadź swoje dane, pozwolą nam one wyliczyć Twoje dzienne zapotrzebowanie na kalorie",
    age: "Wiek",
    weight: "Waga",
    weight_kg: "Waga w kilogramach",
    height: "Wysokość",
    height_cm: "Wysokość w centymetrach",
    gender: "Płeć",
    male: "Mężczyzna",
    objective: "Wprowadż swój cel",
    editGoal: "Edytuj swój cel",
    goalWeight: "Ile chcesz ważyć?",
    goalWeightChange:"Tygodniowa zmiana wagi",
    goalWeightChange1: "0,1 kg",
    goalWeightChange2: "1 kg",
    female: "Kobieta",
    activity: "Aktywność",
    activity_sed: "Siedzący tryb życia",
    activity_act: "Bardzo aktywny",
    continue: "Dalej",
  },
  profile: {
    account: "Konto",
    objective: "Cel",
    objective1: "Utrzymanie wagi",
    objective2: "Utrata masy",
    objective3: "Zwiększenie masy",
    objective_calories:"Dzienne spożycie kalorii:",
    user: "Użytkownik",
    age: "Wiek:",
    weight: "Waga:",
    weight_1: "Waga",
    weight_kg: "Waga w kilogramach",
    height: "Wysokość:",
    height_cm: "Wysokość w centymetrach",
    gender: "Płeć:",
    male: "Mężczyzna",
    female: "Kobieta",
    addNewWeight: "Wprowadź nową wagę",
    cancel: "Anuluj",
    continue: "Kontunuuj",
    save: "Zapisz",
  },
};
