export const pl = {
  common: {
    addProduct: "Dodaj produkt",
    takePhoto: "Zrób zdjęcie",
    addPhoto: "Wybierz zdjęcie",
    addMeal: "Dodaj posiłek",
    addFav: "Dodaj do ulubionych",
    toast: "Proszę wybrać zdjęcie",
    error: "Błąd",
    add: "Dodaj",
  },
  navigation: {
    home: "Strona Główna",
    favorites: "Ulubione",
    profile: "Profil",
    settings: "Ustawienia",
    camera: "Aparat",
  },
  camera: {
    return: "Powrót",
    retakePhoto: "Ponów",
    noAccess: "Brak dostępu do kamery",
  },
  addScreen: {
    name: "Nazwa",
    enterName: "Podaj nazwę",
    calories: "Kalorie",
    enterCalories: "Wpisz wartość kaloryczną na 100g",
    category: "Kategoria",
    enterCategory: "Wpisz kategorię potrawy",
    weight: "Waga",
    enterWeight: "Podaj wagę",
    toastWeight: "Wprowadź wagę posiłku",
    toastCalories: "Wprowadź kaloryczność posiłku",
    loader: "Trwa szacowanie kalorii...",
  },
  editScreen: {
    name: "Nazwa",
    calories: "Kalorie",
    category: "Kategoria",
    edit: "Edytuj",
    editMeal: "Edytuj potrawę",
    delete: "Usuń potrawę",
    weight: "Waga",
  },
  settings: {
    changeLang: "Zmień język",
    selectLang: "Wybierz język",
    eng: "Angielski",
    pl: "Polski",
    darkMode: "Tryb ciemny",
    logOut: "Wyloguj",
  },
};
